language: node_js
node_js:
  - "lts/*"
git:
  quiet: true
branches:
  only:
  - master
services:
  - docker
before_install:
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-radium
install:
  - npm install
script:
  - npm test wdio.conf.js -- --suite login register
cache: npm