language: node_js
node_js:
  - "lts/*"
git:
  quiet: true
branches:
  only:
  - master
services:
  - docker
before_install:
  - docker pull minhpham1990/selenium-grid:1.0
  - docker run -p 4444:4444 --name selenium-grid selegrid:1.0
install:
  - npm install
script:
  - npm test wdio.conf.js -- --suite login register
cache: npm
